apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\ahmed\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Thu, 09 Jul 2026 17:17:04 WAT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://127.0.0.1:63356
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 09 Jul 2026 17:17:04 WAT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: C:\Users\ahmed\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\ahmed\.minikube\profiles\minikube\client.key
